# -*- coding: utf-8 -*-
"""UTS Model Deployment_Inferencing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2Twcjo2wONL3DATJKGMw6iWqm_vlUKy
"""

import pickle
import warnings
warnings.filterwarnings("ignore")

def load_pickle(file):
  with open(file, "rb") as f:
      model= pickle.load(f)
  return model

def prediction(model, sample):
    result= model.predict([sample])
    return result[0]

if __name__ == "__main__":
  file= "xgbclassifier_model.pkl"
  model= load_pickle(file)